version: "3.9"

services:
  postgres_dev:
    image: postgres:16-alpine
    container_name: habit-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_dev_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:16-alpine
    container_name: habit-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: habit_tracker_test
    ports:
      - "5433:5432"
    volumes:
      - pg_test_data:/var/lib/postgresql/data

volumes:
  pg_dev_data:
  pg_test_data: